name: Process GG DRIVE FOLDER
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - index: 1
            url: "https://drive.google.com/drive/folders/1zWinJtXDq4hEL8nr8zS04zTBMdJ9sWZF"
          - index: 2
            url: "https://drive.google.com/drive/folders/1zTKo79rnpx_DLwmDQa7lHZ7CcnoFPAfn"
          - index: 3
            url: "https://drive.google.com/drive/folders/1zNaYhmYR5Ev9rVCZb7aEqkGvxFyTJuR"
          - index: 4
            url: "https://drive.google.com/drive/folders/1zLvDLb1heNzmCEtSF_kIz4IHaVz1do2_"
          - index: 5
            url: "https://drive.google.com/drive/folders/1zDWhQeNhK2myNAsl_fH5tD-J-LgcK4FP"
          - index: 6
            url: "https://drive.google.com/drive/folders/1zC6bBMyZz7bgPgG-feYIw4K6El6nWX7h"
          - index: 7
            url: "https://drive.google.com/drive/folders/1z7LGDOm9vNIwveg44PuChfnXJxnPxRXV"
          - index: 8
            url: "https://drive.google.com/drive/folders/1z0kz5C5xuSTwfNmbVJXY155aoCgty2aI"

      fail-fast: false  # This ensures that the matrix continues running even if some jobs fail.

    continue-on-error: true  # Continue even if matrix jobs fail

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download YouTube playlist
      run: |
         python download_videos.py "${{ matrix.url }}" 
      continue-on-error: true

    - name: Process downloaded videos
      run: |
        python process_videos.py

    - name: Archive processed videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: processed-videos-${{ matrix.index }}
        path: ./processed_videos/
